version: '3.4'

services: 
  api:
    build: 
      context: src/api
      target: dev
    volumes: 
      - ./src/api:/go/src/github.com/philippecarle/mood/api
    ports:
      - "8080:8080"
    links: 
      - rabbitmq
      - mongo
    working_dir: /go/src/github.com/philippecarle/mood/api
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
      JWT_PRIVATE_KEY: CH4NGEM3

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    hostname: rabbit
    volumes:
      - ./config/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./config/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  spacy:
    build: src/worker/spacy
    restart: on-failure
    depends_on: 
      - rabbitmq
    links: 
      - rabbitmq
    volumes: 
      - ./src/worker/spacy:/usr/src/app
    entrypoint: ["python", "main.py"]
